In [2]:

import numpy as np
import pandas as pd
from sklearn.neighbors import KNeighborsClassifier
import sys      


In [51]:
a = pd.read_csv("data.csv",header=None)
b = pd.read_csv("test.csv")
test = np.array(b.loc[0])
print(b)

     0    1    2    3    4    5    6
0  195  133  139  170  177  127  452


In [57]:
numpy = np.array(a) 
retval = [None] * 3                     #array for storing final result
offset = [3,2,2]            #offset for analysing different letters
x = numpy[:,:-1]                        #training data # all rows and all col without last col
y = numpy[:,-1]                         #target data  # only last col and all rows
knn_classifier = KNeighborsClassifier(n_neighbors = 3)
print(y)

['shaurya' 'shaurya' 'shaurya' 'shaurya' 'sen' 'sen']


In [58]:
from sklearn.svm import SVC  
svclassifier = SVC(kernel='linear')  

i = 0
s = 0                                   #starting index for reading word
while i < 3:
    t = np.array(x[:,s:s+offset[i]])
    print(t)
    print("nex")
    svclassifier.fit(t, y)
    
    t1= np.array(test[s:s+offset[i]])
    t1=t1.reshape(1, -1)
    retval[i] = svclassifier.predict(t1)#predcting value and storing in array 
    s = s+offset[i]
    print(s)
    i += 1;                             
                      #increasing offset for pointing to next word
    

[[139 122 152]
 [213 127 150]
 [187 107 148]
 [142 116 178]
 [114 188 318]
 [136 151 357]]
nex
3
[[140 146]
 [124 154]
 [141 158]
 [173 134]
 [121 182]
 [124 280]]
nex
5
[[94 246]
 [88 524]
 [106 266]
 [84 456]
 [206 177]
 [153 156]]
nex
7


In [61]:
i = 0
count = -1
prev = 1
store = retval[0]

retval.sort()                       #sorting predicted values for finding the most repeated person
while i < 2:
    if (retval[i] == retval[i+1]):
        prev += 1
        if(count < prev):
            store = retval[i]       #storing name of person with highest frequency
            count = prev
    else :
        prev = 1;
    i += 1
           
print(store)
                  #flushing value to stdout


['shaurya']
